# Generated by Django 3.1.1 on 2020-09-21 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_QR', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qr',
            name='name',
        ),
    ]
